name: jahzha_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.6
  carousel_slider: ^4.2.1
  font_awesome_flutter: ^10.6.0
  # Local DB
  lottie: ^2.7.0
  shared_preferences: ^2.2.2
  # State Management
  flutter_bloc: ^8.1.3
  # Overlays
  fluttertoast: ^8.2.2
  # Launching Intents
  url_launcher: ^6.2.1
  flutter_share: ^2.0.0
  # Device paths
  path_provider: ^2.1.1
  # Picking files
  image_picker: ^1.0.4
  #  file_picker: ^8.0.3
  # Animation
  animate_do: ^3.0.2
  # SVG Widget
  flutter_svg: ^2.0.9
  # Localization
  easy_localization: ^3.0.3
  # Responsive
  flutter_screenutil: ^5.9.0
  # HTTP Client
  dio: ^5.3.3
  # Caching images
  cached_network_image: ^3.3.0
  # Force update
  neoversion: ^0.0.2
  # Firebase
  firebase_messaging: ^14.6.4
  firebase_core: ^2.14.0
  firebase_crashlytics: ^3.3.3
  firebase_database: ^10.2.3
  # Sounds
  flutter_ringtone_player: ^3.2.0
  # HTML
  flutter_html: ^3.0.0-beta.2
  # UI
  pin_code_fields: ^8.0.1
  flutter_rating_bar: ^4.0.1
  # Google Maps
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  image_cropper: ^4.0.1
  file_picker: ^8.0.0
  # Convert speech to text
  speech_to_text: ^6.3.0
  webview_flutter: ^4.2.2
  smooth_page_indicator: ^1.1.0
  dotted_line: ^3.2.2


dependency_overrides:
  firebase_core_platform_interface: ^4.8.0
  package_info_plus: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/images/playstore.png"
  image_path_ios: "assets/images/appstore.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lottie/
    - assets/fonts/
    - assets/lang/ar.json
    - assets/lang/en.json

  fonts:
    - family: Alexandria
      fonts:
        - asset: assets/fonts/Alexandria-Regular.ttf
          weight: 500
        - asset: assets/fonts/Alexandria-Medium.ttf
          weight: 700
        - asset: assets/fonts/Alexandria-Bold.ttf
          weight: 900


