name: jahzha_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons
  carousel_slider: ^5.0.0
  font_awesome_flutter: ^10.8.0
  # Local DB
  lottie: ^3.0.0
  shared_preferences: ^2.3.5
  # State Management
  flutter_bloc: ^8.1.6
  # Launching Intents
  url_launcher: ^6.3.1
  # Device paths
  path_provider: ^2.1.5
  # Picking files
  image_picker: ^1.1.2
  #  file_picker: ^8.0.3
  # Animation
  animate_do: ^3.3.4
  # SVG Widget
  flutter_svg: ^2.0.9
  # Localization
  easy_localization: ^3.0.7
  # Responsive
  flutter_screenutil: ^5.9.3
  # HTTP Client
  dio: ^5.7.0
  # Caching images
  cached_network_image: ^3.4.1
  # Firebase
  firebase_messaging: ^15.1.6
  firebase_core: ^3.9.0
  # Sounds
  flutter_ringtone_player: ^4.0.0+3
  # HTML
  flutter_html: ^3.0.0-beta.2
  # UI
  pin_code_fields: ^8.0.1
  flutter_rating_bar: ^4.0.1
  file_picker: ^8.1.7
  # Convert speech to text
  webview_flutter: ^4.10.0
  smooth_page_indicator: ^1.2.0+3
  dotted_line: ^3.2.3
  # Map
  google_places_flutter:
    path: ./packages/Google-AutoComplete-TextField-Flutter
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  custom_map_markers: ^0.0.2+1
  world_zipcode_validator: ^0.0.2
  collection: ^1.17.0
  country_code_picker: ^3.1.0
  # Generating QR Code
  qr_flutter: ^4.1.0

dependency_overrides:
  firebase_core_platform_interface: ^4.8.0
  package_info_plus: any
  win32: ^5.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/images/playstore.png"
  image_path_ios: "assets/images/appstore.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lottie/
    - assets/fonts/
    - assets/lang/ar.json
    - assets/lang/en.json
    - assets/images/lottie/
    - shorebird.yaml

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100

    - family: Alexandria
      fonts:
        - asset: assets/fonts/Alexandria-Black.ttf
          weight: 900
        - asset: assets/fonts/Alexandria-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Alexandria-Bold.ttf
          weight: 700
        - asset: assets/fonts/Alexandria-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Alexandria-Medium.ttf
          weight: 500
        - asset: assets/fonts/Alexandria-Regular.ttf
          weight: 400
        - asset: assets/fonts/Alexandria-Light.ttf
          weight: 300
        - asset: assets/fonts/Alexandria-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Alexandria-Thin.ttf
          weight: 100
